#!/bin/bash
# Quick Supabase Setup Script
# Run this to complete the migration

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         SUPABASE MIGRATION - QUICK SETUP GUIDE              ║"
echo "╚════════════════════════════════════════════════════════════════╝"

echo ""
echo "📋 CHECKLIST:"
echo ""
echo "Step 1: Create Supabase Project"
echo "  □ Go to https://supabase.com"
echo "  □ Create new project"
echo "  □ Wait for provisioning"
echo ""

echo "Step 2: Get Connection String"
echo "  □ Go to Settings → Database"
echo "  □ Copy 'Connection String' in URI format"
echo "  □ Format: postgresql://postgres:PASSWORD@db.PROJECT.supabase.co:5432/postgres"
echo ""

echo "Step 3: Update Environment"
echo "  □ Open backend/.env"
echo "  □ Paste CONNECTION STRING into DATABASE_URL"
echo "  □ Save file"
echo ""

echo "Step 4: Install Dependencies"
echo "  Run: pip install -r requirements.txt"
echo ""

echo "Step 5: Initialize Database"
echo "  Run: python supabase_setup.py"
echo ""

echo "Step 6: Verify Setup"
echo "  Check Supabase console for tables:"
echo "  ✓ users"
echo "  ✓ services"
echo "  ✓ documents"
echo "  ✓ document_embeddings"
echo "  ✓ chat_messages"
echo "  ✓ products"
echo "  ✓ faqs"
echo "  ✓ policies"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    WHAT'S BEEN CREATED                      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ FOUNDATION (Ready to use):"
echo "  • requirements.txt - Updated with Supabase packages"
echo "  • models/sqlalchemy_models.py - All ORM models"
echo "  • database.py - SQLAlchemy + Supabase connection"
echo "  • services/vector_service.py - pgvector implementation"
echo "  • supabase_setup.py - Database initialization"
echo "  • .env.supabase - Configuration template"
echo ""

echo "📖 DOCUMENTATION:"
echo "  • SUPABASE_MIGRATION_GUIDE.md - Complete setup guide"
echo "  • SUPABASE_MIGRATION_SUMMARY.md - Technical details"
echo ""

echo "⏳ STILL NEEDED (Next phase):"
echo "  • Update auth_routes.py"
echo "  • Update bot_routes.py"
echo "  • Update document_routes.py"
echo "  • Update rag_routes.py"
echo "  • Update chat_routes.py"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                      SUPERADMIN ACCOUNT                      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Email: superadmin@marketmatic.com"
echo "Password: superadmin"
echo ""

echo "🚀 After setup is complete:"
echo "  1. pip install -r requirements.txt"
echo "  2. python supabase_setup.py"
echo "  3. python app.py (after route updates)"
echo ""

echo "📚 For complete guide: Read SUPABASE_MIGRATION_GUIDE.md"
echo ""
